In [1]:
import os 
import glob
import pandas as pd
import numpy as np

In [2]:
pd.options.display.max_rows = 100
pd.options.display.max_columns = 100

In [3]:
path = pd.read_csv('rec_hgg_path_jan_2019.csv')
path.shape

(353, 34)

In [4]:
## remove the tumor_cell_evaluations that don't have entries
path_withoutNaN = path.dropna(subset = ['tumor_cell_evaluation'])
path_withoutNaN.shape

(226, 34)

In [5]:
## remove duplicates for t_number
path_withoutNaN_noDup = path_withoutNaN.drop_duplicates('t_number')

In [6]:
path_withoutNaN_noDup.shape

(79, 34)

In [7]:
## remove Grade II that are in there accidentally: 
path_withoutNaN_noDup_noGII = path_withoutNaN_noDup[path_withoutNaN_noDup.current_hist_grade != "Grade II"]

In [8]:
path_withoutNaN_noDup_noGII.shape

(79, 34)

In [9]:
path_withoutNaN_noDup_noGII.t_number = path_withoutNaN_noDup_noGII.t_number.astype(int)

In [10]:
path_withoutNaN_noDup_noGII.shape

(79, 34)

In [11]:
path_withoutNaN_noDup_noGII.head()

,b_number,t_number,sf_number,current_scan_date,current_surgery_date,post_t_number,post_scan_date,current_hist_grade,current_hist_type,vial_id,tumor_cell_evaluation,necrosis,mv_hyperplasia,mv_delicate_vasculature,ca9,smi31,f8_delicate,f8_simple,f8_complex,mib_1,gfap_gliosis,cd45,cd68,avgerage_cells,mv_density_overall,gfap_one_cell_type,h_and_e,bx_level_tissue_char,treatment_related_ab,bx_pure_treatment_effect,fields_counted,idh1,macrop_antibody,percent_tumor_nuclei
0,1338,8773,9727.0,2013-10-02,2013-10-03,9877.0,2013-10-04,Grade IV,Glioblastoma,60B60,1,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,2.01,NaN,NaN,NaN,99.0,NaN,NaN,NaN,NaN,NaN,f,NaN,1,NaN,5.0
4,2947,8775,9729.0,2013-10-06,2013-10-07,9878.0,2013-10-08,Grade IV,Glioblastoma,1B61,2,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,34.83,NaN,NaN,NaN,364.0,NaN,NaN,NaN,NaN,NaN,t,NaN,0,NaN,75.0
8,3472,8783,9739.0,2013-10-14,2013-10-15,9880.0,2013-10-16,Treatment Effect,Treatment Effect,31B61,1,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,1.13,NaN,NaN,NaN,198.0,NaN,NaN,NaN,NaN,NaN,t,NaN,0,NaN,20.0
10,3499,8869,9795.0,2013-12-10,2013-12-11,9881.0,2013-12-12,Grade IV,Glioblastoma,65B60,3,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,60.52,NaN,NaN,NaN,331.0,NaN,NaN,NaN,NaN,NaN,f,NaN,1,NaN,95.0
12,3125,8878,9801.0,2013-12-15,2013-12-16,9892.0,2013-12-17,Grade IV,Glioblastoma,42B61,1,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,11.54,NaN,NaN,NaN,231.0,NaN,NaN,NaN,NaN,NaN,t,NaN,0,NaN,10.0

In [12]:
path_withoutNaN_noDup_noGII.b_number = [bnum  if len(str(bnum)) == 4 else "0"+str(bnum)[0:len(bnum)] for bnum in path_withoutNaN_noDup_noGII.b_number.astype(str)]

In [13]:
path_withoutNaN_noDup_noGII.b_number = "b"+path_withoutNaN_noDup_noGII.b_number

In [14]:
path_withoutNaN_noDup_noGII.head()

,b_number,t_number,sf_number,current_scan_date,current_surgery_date,post_t_number,post_scan_date,current_hist_grade,current_hist_type,vial_id,tumor_cell_evaluation,necrosis,mv_hyperplasia,mv_delicate_vasculature,ca9,smi31,f8_delicate,f8_simple,f8_complex,mib_1,gfap_gliosis,cd45,cd68,avgerage_cells,mv_density_overall,gfap_one_cell_type,h_and_e,bx_level_tissue_char,treatment_related_ab,bx_pure_treatment_effect,fields_counted,idh1,macrop_antibody,percent_tumor_nuclei
0,b1338,8773,9727.0,2013-10-02,2013-10-03,9877.0,2013-10-04,Grade IV,Glioblastoma,60B60,1,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,2.01,NaN,NaN,NaN,99.0,NaN,NaN,NaN,NaN,NaN,f,NaN,1,NaN,5.0
4,b2947,8775,9729.0,2013-10-06,2013-10-07,9878.0,2013-10-08,Grade IV,Glioblastoma,1B61,2,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,34.83,NaN,NaN,NaN,364.0,NaN,NaN,NaN,NaN,NaN,t,NaN,0,NaN,75.0
8,b3472,8783,9739.0,2013-10-14,2013-10-15,9880.0,2013-10-16,Treatment Effect,Treatment Effect,31B61,1,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,1.13,NaN,NaN,NaN,198.0,NaN,NaN,NaN,NaN,NaN,t,NaN,0,NaN,20.0
10,b3499,8869,9795.0,2013-12-10,2013-12-11,9881.0,2013-12-12,Grade IV,Glioblastoma,65B60,3,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,60.52,NaN,NaN,NaN,331.0,NaN,NaN,NaN,NaN,NaN,f,NaN,1,NaN,95.0
12,b3125,8878,9801.0,2013-12-15,2013-12-16,9892.0,2013-12-17,Grade IV,Glioblastoma,42B61,1,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,11.54,NaN,NaN,NaN,231.0,NaN,NaN,NaN,NaN,NaN,t,NaN,0,NaN,10.0

In [15]:
path_withoutNaN_noDup_noGII.t_number = "t"+path_withoutNaN_noDup_noGII.t_number.astype(str)

In [16]:
path_withoutNaN_noDup_noGII.head()

,b_number,t_number,sf_number,current_scan_date,current_surgery_date,post_t_number,post_scan_date,current_hist_grade,current_hist_type,vial_id,tumor_cell_evaluation,necrosis,mv_hyperplasia,mv_delicate_vasculature,ca9,smi31,f8_delicate,f8_simple,f8_complex,mib_1,gfap_gliosis,cd45,cd68,avgerage_cells,mv_density_overall,gfap_one_cell_type,h_and_e,bx_level_tissue_char,treatment_related_ab,bx_pure_treatment_effect,fields_counted,idh1,macrop_antibody,percent_tumor_nuclei
0,b1338,t8773,9727.0,2013-10-02,2013-10-03,9877.0,2013-10-04,Grade IV,Glioblastoma,60B60,1,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,2.01,NaN,NaN,NaN,99.0,NaN,NaN,NaN,NaN,NaN,f,NaN,1,NaN,5.0
4,b2947,t8775,9729.0,2013-10-06,2013-10-07,9878.0,2013-10-08,Grade IV,Glioblastoma,1B61,2,0.0,0,NaN,NaN,NaN,NaN,NaN,NaN,34.83,NaN,NaN,NaN,364.0,NaN,NaN,NaN,NaN,NaN,t,NaN,0,NaN,75.0
8,b3472,t8783,9739.0,2013-10-14,2013-10-15,9880.0,2013-10-16,Treatment Effect,Treatment Effect,31B61,1,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,1.13,NaN,NaN,NaN,198.0,NaN,NaN,NaN,NaN,NaN,t,NaN,0,NaN,20.0
10,b3499,t8869,9795.0,2013-12-10,2013-12-11,9881.0,2013-12-12,Grade IV,Glioblastoma,65B60,3,0.0,2,NaN,NaN,NaN,NaN,NaN,NaN,60.52,NaN,NaN,NaN,331.0,NaN,NaN,NaN,NaN,NaN,f,NaN,1,NaN,95.0
12,b3125,t8878,9801.0,2013-12-15,2013-12-16,9892.0,2013-12-17,Grade IV,Glioblastoma,42B61,1,0.0,1,NaN,NaN,NaN,NaN,NaN,NaN,11.54,NaN,NaN,NaN,231.0,NaN,NaN,NaN,NaN,NaN,t,NaN,0,NaN,10.0

In [17]:
## only want to keep the bnums that are in the /archived folder, else won't be able to process them correctly: 
bnums_in_dir = os.listdir('/data/RECglioma/')

In [18]:
bnum_tnum_list = path_withoutNaN_noDup_noGII[['b_number', 't_number']]
bnum_tnum_list.head()

   b_number t_number
0     b1338    t8773
4     b2947    t8775
8     b3472    t8783
10    b3499    t8869
12    b3125    t8878

In [19]:
bnum_tnum_list_indir = bnum_tnum_list[bnum_tnum_list['b_number'].isin(bnums_in_dir) ]

In [20]:
bnum_tnum_list_indir.shape

(79, 2)

In [21]:
bnum_tnum_list_indir['DUMMY']="DUMMY"

In [22]:
bnum_tnum_list_indir.head()

   b_number t_number  DUMMY
0     b1338    t8773  DUMMY
4     b2947    t8775  DUMMY
8     b3472    t8783  DUMMY
10    b3499    t8869  DUMMY
12    b3125    t8878  DUMMY

In [23]:
bnum_tnum_list_indir.to_csv('rec_hgg_process_list.79.csv', index = False, header =False )